// Curated Hong Kong Cantonese hit playlists by year range.
// Each category holds ~100 of the most popular Cantonese songs in HK for that period.
// Audio previews are resolved at runtime from the iTunes Search API (see preview.js).

// ---- Artist favourites (Cantonese only) ----------------------------------
const EASON = [
  { title: '富士山下', artist: '陳奕迅', year: 2006 },
  { title: '浮誇', artist: '陳奕迅', year: 2005 },
  { title: 'K歌之王', artist: '陳奕迅', year: 2000 },
  { title: '明年今日', artist: '陳奕迅', year: 2002 },
  { title: '單車', artist: '陳奕迅', year: 2001 },
  { title: '夕陽無限好', artist: '陳奕迅', year: 2005 },
  { title: '葡萄成熟時', artist: '陳奕迅', year: 2005 },
  { title: '陀飛輪', artist: '陳奕迅', year: 2010 },
  { title: '沙龍', artist: '陳奕迅', year: 2009 },
  { title: '苦瓜', artist: '陳奕迅', year: 2011 },
  { title: '任我行', artist: '陳奕迅', year: 2013 },
  { title: '無條件', artist: '陳奕迅', year: 2015 },
  { title: '無人之境', artist: '陳奕迅', year: 2009 },
  { title: '落花流水', artist: '陳奕迅', year: 2006 },
  { title: '人來人往', artist: '陳奕迅', year: 2002 },
  { title: 'Shall We Talk', artist: '陳奕迅', year: 2001 },
  { title: '最佳損友', artist: '陳奕迅', year: 2005 },
  { title: '我的快樂時代', artist: '陳奕迅', year: 2000 },
  { title: '歲月如歌', artist: '陳奕迅', year: 2003 },
  { title: '十面埋伏', artist: '陳奕迅', year: 2003 },
  { title: '阿牛', artist: '陳奕迅', year: 2006 },
  { title: '綿綿', artist: '陳奕迅', year: 2001 },
  { title: '孤獨探戈', artist: '陳奕迅', year: 2005 },
  { title: '六月飛霜', artist: '陳奕迅', year: 2011 },
  { title: '天下無雙', artist: '陳奕迅', year: 2001 },
  { title: '與我常在', artist: '陳奕迅', year: 2000 },
  { title: '黑暗中漫舞', artist: '陳奕迅', year: 2001 },
  { title: '失戀太少', artist: '陳奕迅', year: 2001 },
  { title: '七百年後', artist: '陳奕迅', year: 2009 },
  { title: '幸福摩天輪', artist: '陳奕迅', year: 2000 },
  { title: '一絲不掛', artist: '陳奕迅', year: 2010 },
  { title: '大開眼戒', artist: '陳奕迅', year: 2001 },
  { title: '1874', artist: '陳奕迅', year: 2005 },
  { title: '反高潮', artist: '陳奕迅', year: 2001 },
  { title: '防不勝防', artist: '陳奕迅', year: 2001 },
  { title: '粵語殘片', artist: '陳奕迅', year: 2001 },
  { title: '今天只做一件事', artist: '陳奕迅', year: 2001 },
  { title: '今日', artist: '陳奕迅', year: 2005 },
  { title: '四季', artist: '陳奕迅', year: 2016 },
  { title: '黃金時代', artist: '陳奕迅', year: 2001 },
  { title: '重口味', artist: '陳奕迅', year: 2012 },
  { title: '碌卡', artist: '陳奕迅', year: 2012 },
  { title: '主旋律', artist: '陳奕迅', year: 2013 },
  { title: '告別娑婆', artist: '陳奕迅', year: 2013 },
  { title: '暴殄天物', artist: '陳奕迅', year: 2008 },
  { title: '怕死', artist: '陳奕迅', year: 2008 },
  { title: '心深傷透', artist: '陳奕迅', year: 2006 },
  { title: '我不好愛', artist: '陳奕迅', year: 2006 },
  { title: '完', artist: '陳奕迅', year: 2010 },
  { title: '張氏情歌', artist: '陳奕迅', year: 2011 },
  { title: '吟遊詩人', artist: '陳奕迅', year: 2011 },
  { title: '致明日的舞', artist: '陳奕迅', year: 2020 },
  { title: '是但求其愛', artist: '陳奕迅', year: 2020 },
  { title: '你給我聽好', artist: '陳奕迅', year: 2020 },
  { title: '人啊人', artist: '陳奕迅', year: 2022 },
  { title: '塵大師', artist: '陳奕迅', year: 2023 },
  { title: '盲婚啞嫁', artist: '陳奕迅', year: 2023 }
]

const ENDY = [
  { title: '星塵', artist: '周國賢', year: 2014 },
  { title: '橡筋', artist: '周國賢', year: 2016 },
  { title: '物極必反', artist: '周國賢', year: 2017 },
  { title: '時空', artist: '周國賢', year: 2018 },
  { title: '有時', artist: '周國賢', year: 2015 },
  { title: '未完 待續', artist: '周國賢', year: 2018 },
  { title: '地下街', artist: '周國賢', year: 2006 },
  { title: '目黑', artist: '周國賢', year: 2006 },
  { title: '14天', artist: '周國賢', year: 2012 },
  { title: '漢城沉沒了', artist: '周國賢', year: 2010 },
  { title: '離魂記', artist: '周國賢', year: 2015 },
  { title: 'Children Song', artist: '周國賢', year: 2016 },
  { title: '赤城千葉', artist: '周國賢', year: 2012 },
  { title: '密封罩', artist: '周國賢', year: 2014 },
  { title: 'Fall', artist: '周國賢', year: 2019 },
  { title: '塵世美', artist: '周國賢', year: 2021 },
  { title: '太平道', artist: '周國賢', year: 2013 },
  { title: '身後身', artist: '周國賢', year: 2021 },
  { title: '雙兒', artist: '周國賢', year: 2022 },
  { title: '鬼怒川', artist: '周國賢', year: 2015 },
  { title: '模稜兩可', artist: '周國賢', year: 2016 },
  { title: '不敵', artist: '周國賢', year: 2016 },
  { title: '黑眼圈', artist: '周國賢', year: 2014 },
  { title: '東區走廊', artist: '周國賢', year: 2014 },
  { title: 'Dreamcatcher', artist: '周國賢', year: 2017 },
  { title: '今生不回家', artist: '周國賢', year: 2020 },
  { title: '再見有時', artist: '周國賢', year: 2024 },
  { title: '逃生門', artist: '周國賢', year: 2020 },
  { title: '好自為之', artist: '周國賢', year: 2021 },
  { title: '我們都不是無辜的', artist: '周國賢', year: 2019 },
  { title: '極樂', artist: '周國賢', year: 2021 },
  { title: '天馬行空', artist: '周國賢', year: 2017 },
  // The 10 songs below replaced tracks that iTunes HK has no preview for
  // (天秤 / 從此世界多了一分鐘 / 覺醒字幕組 / 陽光點的歌 / 溫室氣體 /
  //  永遠很近 / 撲火 / 我是傳奇 / 無畏 / 童話) so every entry is playable.
  { title: '守口如瓶', artist: '周國賢', year: 2018 },
  { title: '錢七', artist: '周國賢', year: 2018 },
  { title: '在天之靈', artist: '周國賢', year: 2017 },
  { title: '凡夫的樂章', artist: '周國賢', year: 2019 },
  { title: '年輕人們', artist: '周國賢', year: 2015 },
  { title: '當下的力量', artist: '周國賢', year: 2018 },
  { title: '消化不良', artist: '周國賢', year: 2016 },
  { title: '雷克雅未克', artist: '麥浚龍、周國賢', year: 2015 },
  { title: '愛比死更冷', artist: '周國賢', year: 2016 },
  { title: '天涯', artist: '周國賢', year: 2024 }
]

const TERENCE = [
  { title: '一人之境', artist: '林家謙', year: 2020 },
  { title: '特倫斯夢遊仙境', artist: '林家謙', year: 2020 },
  { title: '時光倒流一句話', artist: '林家謙', year: 2020 },
  { title: '拼命無恙', artist: '林家謙', year: 2020 },
  { title: '下一位前度', artist: '林家謙', year: 2019 },
  { title: '神奇的糊塗魔藥', artist: '林家謙', year: 2021 },
  { title: '在空中的這一秒', artist: '林家謙', year: 2021 },
  { title: '難道喜歡處女座', artist: '林家謙', year: 2021 },
  { title: '聽風', artist: '林家謙', year: 2021 },
  { title: '拋物線', artist: '林家謙', year: 2020 },
  { title: 'just carry on', artist: '林家謙', year: 2020 },
  { title: '某種老朋友', artist: '林家謙', year: 2022 },
  { title: '記得', artist: '林家謙', year: 2022 },
  { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
  { title: '夏之風物詩', artist: '林家謙', year: 2022 },
  { title: 'doodoodoo', artist: '林家謙', year: 2022 },
  { title: '小林不動產', artist: '林家謙', year: 2023 },
  { title: '怪我只敢做好人', artist: '林家謙', year: 2023 },
  { title: '萬一你是個好人', artist: '林家謙', year: 2023 },
  { title: '流離者的海', artist: '林家謙', year: 2023 },
  { title: '你的世界', artist: '林家謙', year: 2023 },
  { title: '靈魂出竅練習曲', artist: '林家謙', year: 2023 },
  { title: '無答案', artist: '林家謙', year: 2024 },
  { title: '喃嘸師感官漫遊', artist: '林家謙', year: 2024 },
  { title: '普渡眾生', artist: '林家謙', year: 2024 },
  { title: '春日部', artist: '林家謙', year: 2024 },
  { title: '四月物語', artist: '林家謙', year: 2025 },
  { title: '夏日之子', artist: '林家謙', year: 2025 },
  { title: '秋葉緣', artist: '林家謙', year: 2025 },
  { title: '冬季限定', artist: '林家謙', year: 2025 },
  { title: '每當變幻時', artist: '林家謙', year: 2025 }
]

// ---- Optional artist groups (can be filtered out at play time) -------------
// These are NOT removed from the playlist; players choose whether to include
// them. Group membership is matched per artist token, so collaborations such as
// "古巨基、呂爵安" or "姜濤、AGA" are recognised too.
export const ARTIST_GROUPS = [
  {
    id: 'mirror',
    label: 'MIRROR',
    description: 'MIRROR 及其全部成員',
    members: [
      'MIRROR',
      '陳瑞輝', '王智德', '楊樂文', '邱士縉', '江𤒹生', '柳應廷',
      '陳卓賢', '盧瀚霆', '李駿傑', '呂爵安', '姜濤', '邱傲然'
    ]
  }
]

// Split "張天賦、陳蕾" / "A & B" / "X feat. Y" into individual artist names.
export function artistTokens(artist) {
  return String(artist || '')
    .split(/[、,，&/]|feat\.|ft\./i)
    .map((s) => s.trim())
    .filter(Boolean)
}

// Does this song have any artist belonging to the given group?
export function songInGroup(song, group) {
  if (!group) return false
  return artistTokens(song.artist).some((t) => group.members.includes(t))
}

// Extra hits added to dilute the year playlists (see ARTIST_GROUPS / MIRROR filter).
const BACKFILL_2020_2022 = [
  { title: 'ALL WE HAVE IS NOW', artist: '方皓玟', year: 2020 },
  { title: '溝渠暢泳', artist: '泳兒', year: 2020 },
  { title: '十字路口', artist: '胡鴻鈞', year: 2020 },
  { title: '放心吧! 爸媽不在家', artist: '神奇膠', year: 2020 },
  { title: '佚名', artist: '梁釗峰', year: 2020 },
  { title: '痛', artist: '許廷鏗', year: 2020 },
  { title: '謝謝對不起', artist: '許靖韻', year: 2020 },
  { title: '小謊言', artist: '連詩雅', year: 2020 },
  { title: '好好的過 (Have a Nice Life)', artist: '陳葦廷', year: 2020 },
  { title: '不能放手', artist: '菊梓喬', year: 2020 },
  { title: '遠在眼前', artist: '馮允謙', year: 2020 },
  { title: '平凡海賊王', artist: '劉卓軒', year: 2020 },
  { title: '原來有愛', artist: '譚嘉儀', year: 2020 },
  { title: '未開始已經結束', artist: 'Dear Jane', year: 2020 },
  { title: '南洋別戀', artist: 'The Boogie Playboys', year: 2020 },
  { title: '時間的初衷', artist: 'ToNick', year: 2020 },
  { title: '深夜告別練習', artist: 'Zpecial', year: 2020 },
  { title: '想再和你看煙花', artist: '布志綸', year: 2021 },
  { title: '勿念', artist: '岑寧兒', year: 2021 },
  { title: '日出時讓街燈安睡', artist: '李幸倪', year: 2021 },
  { title: '我要和你在一起', artist: '谷婭溦', year: 2021 },
  { title: '鐵樹', artist: '林欣彤', year: 2021 },
  { title: '時間的囚犯', artist: '林奕匡', year: 2021 },
  { title: '愛因斯坦羅森橋', artist: '林家謙', year: 2021 },
  { title: '只是太愛你', artist: '張敬軒', year: 2021 },
  { title: '孤勇者', artist: '陳奕迅', year: 2021 },
  { title: '我想和你好好的', artist: '陳蕾', year: 2021 },
  { title: '我不是邱比特', artist: '曾比特', year: 2021 },
  { title: 'It’s OK To Be Sad', artist: '衛蘭', year: 2021 },
  { title: '萬物有時', artist: '鄭秀文', year: 2021 },
  { title: '最難行的路', artist: '鄭欣宜', year: 2021 },
  { title: '未見過世面的招積', artist: '謝安琪', year: 2021 },
  { title: '好好珍惜自己', artist: '鍾嘉欣', year: 2021 },
  { title: '那些傷我也有過', artist: '關心妍', year: 2021 },
  { title: '西遊記', artist: 'JB', year: 2021 },
  { title: '摯愛 A Letter To...', artist: 'Novel Friday', year: 2021 },
  { title: '孤獨之塔', artist: 'per se', year: 2021 },
  { title: '好好地過', artist: 'RubberBand', year: 2021 },
  { title: '我在流浮山滴眼水.jpg', artist: 'Serrini', year: 2021 },
  { title: '愛回家', artist: '古巨基', year: 2022 },
  { title: '土撥鼠之日', artist: '吳林峰', year: 2022 },
  { title: 'Goodnight My Love', artist: '林德信', year: 2022 },
  { title: '如風', artist: '炎明熹', year: 2022 },
  { title: '靈魂伴侶', artist: '姚焯菲', year: 2022 },
  { title: '及時行樂', artist: '洪嘉豪', year: 2022 },
  { title: '連續劇', artist: '容祖兒', year: 2022 },
  { title: 'Frenemy', artist: '張天賦', year: 2022 },
  { title: '多謝恐懼', artist: '陳明憙', year: 2022 },
  { title: '命盡頭', artist: '陳柏宇', year: 2022 },
  { title: '厭惡物圖鑑', artist: '陳健安', year: 2022 },
  { title: 'Long D', artist: '陳凱詠', year: 2022 },
  { title: '泰姬', artist: '陳慧敏', year: 2022 },
  { title: '世界以痛吻我而我歌唱', artist: '黃妍', year: 2022 },
  { title: '人間英靈', artist: '葉巧琳', year: 2022 },
  { title: 'Tomorrow', artist: 'AGA', year: 2022 },
  { title: 'confidence', artist: 'Gareth.T', year: 2022 },
  { title: '早晨', artist: 'Jan Curious', year: 2022 },
  { title: '你是我捱過困境的勇氣', artist: 'JNYBeatz', year: 2022 },
  { title: '後備 2.0', artist: 'Tiab', year: 2022 },
  { title: '2nd Favourite 第二最愛', artist: 'Tyson Yoshi', year: 2022 },
  { title: '二話都說', artist: 'WHIZZ', year: 2022 },
  { title: '精神流亡', artist: 'Zarahn', year: 2022 },
]

// Extra hits added to dilute the year playlists (see ARTIST_GROUPS / MIRROR filter).
const BACKFILL_2022_2024 = [
  { title: 'It\'s not your fault', artist: '方皓玟', year: 2023 },
  { title: '捱麵包的人', artist: '吳林峰', year: 2023 },
  { title: '想跟你好好道別我怕來不及', artist: '吳業坤', year: 2023 },
  { title: '一個人走走', artist: '岑寧兒', year: 2023 },
  { title: '企好', artist: '李幸倪', year: 2023 },
  { title: '城市迷霧', artist: '谷婭溦', year: 2023 },
  { title: '一了百了', artist: '泳兒', year: 2023 },
  { title: '今生今世', artist: '炎明熹', year: 2023 },
  { title: '世一 (不可一世)', artist: '張天賦', year: 2023 },
  { title: '隱形遊樂場 (情緒過山車)', artist: '張敬軒', year: 2023 },
  { title: '良心發現', artist: '許廷鏗', year: 2023 },
  { title: '焦焦焦', artist: '陳奕迅', year: 2023 },
  { title: '好好掛住', artist: '陳健安', year: 2023 },
  { title: '神的不在場證明', artist: '陳蕾', year: 2023 },
  { title: '給你幸福 所以幸福', artist: '馮允謙', year: 2023 },
  { title: '日光漂白', artist: '黃妍', year: 2023 },
  { title: '綜藝魂', artist: '葉巧琳', year: 2023 },
  { title: '沒有位置未有人', artist: '劉卓軒', year: 2023 },
  { title: '愛是… 2.0', artist: '鄭秀文', year: 2023 },
  { title: 'Believe Us', artist: '鄭欣宜', year: 2023 },
  { title: '成婚破浪', artist: '謝安琪', year: 2023 },
  { title: '絕', artist: '譚嘉儀', year: 2023 },
  { title: 'Special One', artist: 'AGA', year: 2023 },
  { title: '最佳女團友', artist: 'Beanies', year: 2023 },
  { title: '懷舊金曲之夜', artist: 'Dear Jane', year: 2023 },
  { title: '52赫茲', artist: 'KOLOR', year: 2023 },
  { title: '票房毒藥', artist: 'Nowhere Boys', year: 2023 },
  { title: '我們的故事未完...待續', artist: 'per se', year: 2023 },
  { title: 'Be Right Back', artist: 'RubberBand', year: 2023 },
  { title: '垃圾女星', artist: 'Serrini', year: 2023 },
  { title: '記得梳頭', artist: 'ToNick', year: 2023 },
  { title: '你不會一輩子的愛上我', artist: 'Tyson Yoshi', year: 2023 },
  { title: '下一世つづく', artist: 'YEAHS', year: 2023 },
  { title: '成長的錯', artist: '古巨基', year: 2024 },
  { title: '晨星', artist: '周殷廷', year: 2024 },
  { title: '有你聽我的故事', artist: '林家謙', year: 2024 },
  { title: '愛在三千的宇宙', artist: '林峯', year: 2024 },
  { title: '至少他不似你', artist: '姚焯菲', year: 2024 },
  { title: '漫天星', artist: '洪嘉豪', year: 2024 },
  { title: 'One Last Time', artist: '容祖兒', year: 2024 },
  { title: '作賤。矛盾', artist: '許靖韻', year: 2024 },
  { title: '百妖夜行的修行 FREAKS NIGHT PARADE', artist: '陳凱詠', year: 2024 },
  { title: '傾城', artist: '曾比特', year: 2024 },
  { title: '慢性分手', artist: '雲浩影', year: 2024 },
  { title: '白髮齊眉', artist: '鄧小巧', year: 2024 },
  { title: 'Let go', artist: '歸綽嶢', year: 2024 },
  { title: '傢俬', artist: '魏浚笙', year: 2024 },
  { title: '去北極忘記你', artist: 'Gareth.T', year: 2024 },
  { title: '傷心的時候別說話', artist: 'Kiri T', year: 2024 },
  { title: '最佳食用日期', artist: 'KOWLOON K', year: 2024 },
  { title: '拾回鐵達尼', artist: 'OneUp', year: 2024 },
  { title: '緊急應變逃生法', artist: 'Pandora', year: 2024 },
  { title: '98', artist: 'The Hertz', year: 2024 },
  { title: 'Because of You', artist: 'Tiab', year: 2024 },
  { title: 'Aren\'t You Thinking of ___?', artist: 'WHIZZ', year: 2024 },
  { title: '不理痛', artist: 'Zpecial', year: 2024 },
]

// Extra hits added to dilute the year playlists (see ARTIST_GROUPS / MIRROR filter).
const BACKFILL_2024_2026 = [
  { title: '喂起身!', artist: '布志綸', year: 2025 },
  { title: '瘋子', artist: '吳林峰', year: 2025 },
  { title: '還剩一件未做的事', artist: '吳業坤', year: 2025 },
  { title: '隨時隨地', artist: '李幸倪', year: 2025 },
  { title: '想和你', artist: '周殷廷', year: 2025 },
  { title: '那些不愛我的人', artist: '林奕匡', year: 2025 },
  { title: '九月·半晴', artist: '林家謙', year: 2025 },
  { title: '砂之曼陀羅', artist: '林峯', year: 2025 },
  { title: '老殘遊戲', artist: '泳兒', year: 2025 },
  { title: 'KMC', artist: '姚焯菲', year: 2025 },
  { title: '畜生', artist: '洪嘉豪', year: 2025 },
  { title: '但你要甜', artist: '容祖兒', year: 2025 },
  { title: '目擊者', artist: '張天賦', year: 2025 },
  { title: '我看見今晚的月色很美,你呢?', artist: '晚安莉莉', year: 2025 },
  { title: 'BELONGING', artist: '陳明憙', year: 2025 },
  { title: '一天', artist: '陳柏宇', year: 2025 },
  { title: '不遲不早', artist: '陳健安', year: 2025 },
  { title: '西湖 Xihu', artist: '陳凱詠', year: 2025 },
  { title: '不明文規定', artist: '陳蕾', year: 2025 },
  { title: '我們還有幾多時間', artist: '雲浩影', year: 2025 },
  { title: '手繪黑卡', artist: '馮允謙', year: 2025 },
  { title: '其實我 不是那麼的純情', artist: '黃妍', year: 2025 },
  { title: '小傷疤', artist: '葉巧琳', year: 2025 },
  { title: 'Seeds of Truth', artist: '詹天文', year: 2025 },
  { title: '其實痛是你的想像', artist: '鄧小巧', year: 2025 },
  { title: '城光遂夢', artist: '謝安琪', year: 2025 },
  { title: '一生懸命', artist: '魏浚笙', year: 2025 },
  { title: 'The Lost Sunglasses', artist: 'AGA', year: 2025 },
  { title: '成就解鎖', artist: 'Billy Choi', year: 2025 },
  { title: '頹廢員工手冊', artist: 'Cozy Syndrome', year: 2025 },
  { title: '如何變回不知道', artist: 'Dear Jane', year: 2025 },
  { title: '跟悲傷結了帳', artist: 'Gareth.T', year: 2025 },
  { title: '我可能是迴避型', artist: 'Kiri T', year: 2025 },
  { title: '給勝利者的一封信', artist: 'Nowhere Boys', year: 2025 },
  { title: '善良之歌', artist: 'Pandora', year: 2025 },
  { title: '差一點你就是永遠', artist: 'per se', year: 2025 },
  { title: '容許我為你鬆手', artist: 'ROVER', year: 2025 },
  { title: '搲撈HK', artist: 'RubberBand', year: 2025 },
  { title: '掌心的女孩', artist: 'Serrini', year: 2025 },
  { title: 'Re: 末世情書', artist: 'The Hertz', year: 2025 },
  { title: '⁠1994', artist: 'Tyson Yoshi', year: 2025 },
  { title: 'Hey Darling Darling, Fill My Empty Soul', artist: 'WHIZZ', year: 2025 },
  { title: '流星劃過富士山', artist: 'YEAHS', year: 2025 },
  { title: '其實最怕寫情歌', artist: 'Zpecial', year: 2025 },
  { title: 'How could you?', artist: '歸綽嶢', year: 2026 },
]

// Raw three-year buckets: the source of truth for song data. The user-facing
// year categories are generated per calendar year from these (see below).
const YEAR_BUCKETS = [
  {
    id: '2020-2022',
    label: '2020–2022',
    range: '2020 - 2022',
    description: '2020 至 2022 年最紅粵語歌',
    songs: [
      { title: '記憶棉', artist: '張天賦', year: 2021 },
      { title: 'E先生 連環不幸事件', artist: '呂爵安', year: 2021 },
      { title: 'Dear My Friend,', artist: '姜濤', year: 2021 },
      { title: '一人之境', artist: '林家謙', year: 2020 },
      { title: '呼吸有害', artist: '莫文蔚', year: 2020 },
      { title: '銀河修理員', artist: 'Dear Jane', year: 2020 },
      { title: '作品的說話', artist: '姜濤', year: 2022 },
      { title: '小心地滑', artist: '張天賦', year: 2022 },
      { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
      { title: '到底發生過什麼事', artist: 'Dear Jane', year: 2022 },
      { title: '老派約會之必要', artist: '張天賦', year: 2022 },
      { title: '留一天與你喘息', artist: '陳卓賢', year: 2022 },
      { title: '俏郎君', artist: '張敬軒', year: 2021 },
      { title: '反對無效', artist: '張天賦', year: 2021 },
      { title: '蒙著嘴說愛你', artist: '姜濤', year: 2020 },
      { title: '是但求其愛', artist: '陳奕迅', year: 2020 },
      { title: 'BOSS', artist: 'MIRROR', year: 2021 },
      { title: 'Ciao', artist: 'RubberBand', year: 2021 },
      { title: '小諧星', artist: '呂爵安', year: 2021 },
      { title: '不可愛教主', artist: '盧瀚霆', year: 2021 },
      { title: 'Megahit', artist: '盧瀚霆', year: 2021 },
      { title: 'WARRIOR', artist: 'MIRROR', year: 2021 },
      { title: 'IGNITED', artist: 'MIRROR', year: 2020 },
      { title: 'Master Class', artist: '姜濤', year: 2021 },
      { title: '神奇的糊塗魔藥', artist: '林家謙', year: 2021 },
      { title: '狂人日記', artist: '柳應廷', year: 2021 },
      { title: '鏡中鏡', artist: '姜濤', year: 2022 },
      { title: '賽勒斯的愛', artist: '張敬軒', year: 2022 },
      { title: '人啊人', artist: '陳奕迅', year: 2022 },
      { title: '多喝水', artist: '鄭融', year: 2021 },
      { title: '先哭為敬', artist: '鄭欣宜', year: 2021 },
      { title: '留下來的人', artist: 'C AllStar', year: 2021 },
      { title: '東京人壽', artist: '容祖兒', year: 2020 },
      { title: '地球來的人', artist: '馮允謙', year: 2020 },
      { title: '無力感', artist: '許廷鏗', year: 2020 },
      { title: 'See You Next Time', artist: 'AGA', year: 2020 },
      { title: '暫定', artist: '關智斌', year: 2020 },
      { title: '感情這回事', artist: '陳柏宇', year: 2020 },
      { title: '零分', artist: 'JUDE', year: 2020 },
      { title: '哀的美敦書', artist: 'Dear Jane', year: 2020 },
      { title: '人話', artist: '方皓玟', year: 2020 },
      { title: '風的形狀', artist: '岑寧兒', year: 2021 },
      { title: '集合吧！地球保衛隊', artist: 'C AllStar', year: 2021 },
      { title: '荊棘海', artist: '泳兒', year: 2021 },
      { title: '係咁先啦', artist: 'MC $oHo & KidNey', year: 2021 },
      { title: '一表人才', artist: '呂爵安、邱鋒澤', year: 2021 },
      { title: 'My Apple Pie', artist: '呂爵安', year: 2021 },
      { title: '時光倒流一句話', artist: '林家謙', year: 2020 },
      { title: '離不開', artist: '謝安琪', year: 2021 },
      { title: '風雨不改', artist: '姜濤', year: 2022 },
      { title: '永順街39號', artist: '盧瀚霆', year: 2022 },
      { title: 'Elevator', artist: '呂爵安', year: 2022 },
      { title: '離別的規矩', artist: '柳應廷', year: 2022 },
      { title: '人類群星閃耀時', artist: '柳應廷', year: 2021 },
      { title: 'DWBF', artist: '陳卓賢', year: 2021 },
      { title: '神隊友', artist: '盧瀚霆', year: 2020 },
      { title: '正式開始', artist: '陳卓賢', year: 2020 },
      { title: 'Distance', artist: '陳卓賢', year: 2022 },
      { title: '地球上的最後一朵花', artist: '陳卓賢', year: 2022 },
      { title: 'King Kong', artist: '盧瀚霆', year: 2022 },
      { title: '飄流教室', artist: '古巨基、呂爵安', year: 2022 },
      { title: '自我安慰', artist: '古巨基、張天賦', year: 2022 },
      { title: 'We All Are', artist: 'MIRROR', year: 2022 },
      { title: 'Never-never Land', artist: 'COLLAR', year: 2022 },
      { title: '第二最愛', artist: '古巨基、Tyson Yoshi', year: 2022 },
      { title: 'I Know', artist: '姜濤', year: 2021 },
      { title: '隔離', artist: '陳凱詠', year: 2020 },
      { title: '別為我好', artist: '許靖韻、林奕匡', year: 2020 },
      { title: '凡人不懂愛', artist: '胡鴻鈞', year: 2020 },
      { title: '沒身份妒忌', artist: '胡鴻鈞', year: 2020 },
      { title: '拼命無恙', artist: '林家謙', year: 2020 },
      { title: '我們的基因', artist: '謝安琪', year: 2020 },
      { title: '逃生門', artist: '周國賢', year: 2020 },
      { title: '難道喜歡處女座', artist: '林家謙', year: 2021 },
      { title: '思念即地獄', artist: '馮允謙', year: 2021 },
      { title: '人類不宜飛行', artist: 'Dear Jane', year: 2021 },
      { title: '聖馬力諾之心', artist: 'Dear Jane', year: 2021 },
      { title: '網絡安全隱患', artist: 'Serrini', year: 2020 },
      { title: '離原', artist: 'Serrini', year: 2021 },
      { title: '真話的清高', artist: '炎明熹', year: 2021 },
      { title: '焰', artist: '炎明熹', year: 2022 },
      { title: '我不如', artist: '曾比特', year: 2021 },
      { title: '逆時車站', artist: '洪嘉豪', year: 2021 },
      { title: '理性與任性之間', artist: 'AGA', year: 2021 },
      { title: '幸福門', artist: '李幸倪', year: 2020 },
      { title: '睡到三點', artist: '193', year: 2021 },
      { title: '哭牆', artist: '谷婭溦', year: 2020 },
      { title: '突如其來的心跳感覺', artist: '盧瀚霆、呂爵安', year: 2021 },
      { title: '黑之呼吸', artist: '江𤒹生', year: 2021 },
      { title: '我們很帥', artist: 'ERROR', year: 2021 },
      { title: '低半度', artist: '衛蘭', year: 2020 },
      { title: '原來談戀愛是這麼一回事', artist: '姚焯菲', year: 2021 },
      { title: '下流社會', artist: '陳蕾', year: 2022 },
      { title: '凡星', artist: '陳蕾', year: 2022 },
      { title: '豐乳肥臀', artist: '鄭欣宜', year: 2022 },
      { title: '我地', artist: '鄭欣宜', year: 2022 },
      { title: '憶年', artist: '謝安琪', year: 2022 },
      { title: '笑住喊', artist: 'Gareth.T', year: 2022 },
      { title: '我也難過的', artist: '吳林峰、謝芊彤', year: 2022 },
      { title: "Freakin' Nightmare", artist: '馮允謙', year: 2022 },
      ...BACKFILL_2020_2022
    ]
  },
  {
    id: '2022-2024',
    label: '2022–2024',
    range: '2022 - 2024',
    description: '2022 至 2024 年最紅粵語歌',
    songs: [
      { title: '濤', artist: '姜濤', year: 2023 },
      { title: '作品的說話', artist: '姜濤', year: 2022 },
      { title: '好得太過份', artist: '姜濤', year: 2024 },
      { title: '隱形遊樂場', artist: '張敬軒', year: 2023 },
      { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
      { title: '會再見的', artist: '馮允謙', year: 2024 },
      { title: '到底發生過什麼事', artist: 'Dear Jane', year: 2022 },
      { title: '老派約會之必要', artist: '張天賦', year: 2022 },
      { title: '小心地滑', artist: '張天賦', year: 2022 },
      { title: '留一天與你喘息', artist: '陳卓賢', year: 2022 },
      { title: 'Dummy', artist: '姜濤', year: 2023 },
      { title: '黑玻璃', artist: '洪嘉豪', year: 2024 },
      { title: '世一', artist: '張天賦', year: 2023 },
      { title: '與我無關', artist: '張天賦', year: 2023 },
      { title: '以孤獨命名', artist: '陳卓賢', year: 2024 },
      { title: '偷情', artist: '盧瀚霆', year: 2023 },
      { title: '鏡中鏡', artist: '姜濤', year: 2022 },
      { title: '普渡眾生', artist: '林家謙', year: 2024 },
      { title: '岩巉', artist: '姜濤', year: 2023 },
      { title: '黑月', artist: '姜濤', year: 2024 },
      { title: '追', artist: '姜濤', year: 2023 },
      { title: '抽', artist: '張天賦', year: 2023 },
      { title: '永順街39號', artist: '盧瀚霆', year: 2022 },
      { title: 'Every Single Time', artist: '姜濤', year: 2024 },
      { title: '風雨不改', artist: '姜濤', year: 2022 },
      { title: '再見 寧靜海', artist: '陳卓賢', year: 2023 },
      { title: '小心碰頭', artist: '張天賦', year: 2024 },
      { title: '隔牆有耳', artist: '張天賦', year: 2024 },
      { title: '某種老朋友', artist: '林家謙', year: 2022 },
      { title: '青春告別式', artist: '張敬軒', year: 2024 },
      { title: '賽勒斯的愛', artist: '張敬軒', year: 2022 },
      { title: '間歇性休眠', artist: '陳凱詠', year: 2024 },
      { title: '九秒九', artist: '容祖兒', year: 2024 },
      { title: '回憶半分鐘', artist: '雲浩影', year: 2024 },
      { title: 'Dum Dum', artist: '李幸倪', year: 2023 },
      { title: '伸縮自如的愛', artist: '陳蕾', year: 2023 },
      { title: '下流社會', artist: '陳蕾', year: 2022 },
      { title: '至少做一件離譜的事', artist: 'Kiri T', year: 2024 },
      { title: '一把火', artist: 'Lolly Talk', year: 2023 },
      { title: '不如散步', artist: 'RubberBand', year: 2023 },
      { title: '收到收到', artist: '馮允謙', year: 2023 },
      { title: '報復式浪漫', artist: '馮允謙', year: 2022 },
      { title: '救命稻草', artist: '張天賦', year: 2023 },
      { title: '永久損毀', artist: '張天賦、陳蕾', year: 2023 },
      { title: '人啊人', artist: '陳奕迅', year: 2022 },
      { title: '盲婚啞嫁', artist: '陳奕迅', year: 2023 },
      { title: '憶年', artist: '謝安琪', year: 2022 },
      { title: '笑住喊', artist: 'Gareth.T', year: 2022 },
      { title: '我也難過的', artist: '吳林峰、謝芊彤', year: 2022 },
      { title: "Freakin' Nightmare", artist: '馮允謙', year: 2022 },
      { title: 'Little Magic', artist: '炎明熹', year: 2023 },
      { title: '仍然是那個少年', artist: '陳健安', year: 2023 },
      { title: '戀愛腦之死', artist: '陳健安', year: 2024 },
      { title: '藝術與科學', artist: '林奕匡、黃妍、葉巧琳', year: 2024 },
      { title: 'Elevator', artist: '呂爵安', year: 2022 },
      { title: 'LOVERSE', artist: '呂爵安', year: 2023 },
      { title: 'E先生 愛人執照', artist: '呂爵安', year: 2023 },
      { title: '油麻地莎士比亞', artist: '呂爵安', year: 2024 },
      { title: '月光奏明曲', artist: '呂爵安', year: 2024 },
      { title: '漸漸我們', artist: '呂爵安、陳凱詠', year: 2024 },
      { title: 'Again!', artist: '呂爵安', year: 2023 },
      { title: 'MONEY', artist: '盧瀚霆', year: 2023 },
      { title: 'Hey Hey OK!', artist: '盧瀚霆', year: 2024 },
      { title: '深閨', artist: '盧瀚霆', year: 2024 },
      { title: 'MY LIFE', artist: '盧瀚霆', year: 2024 },
      { title: '致我', artist: '盧瀚霆', year: 2024 },
      { title: '浪漫殺死巨蟹座', artist: '盧瀚霆', year: 2023 },
      { title: 'Mr. Stranger', artist: '盧瀚霆', year: 2022 },
      { title: 'King Kong', artist: '盧瀚霆', year: 2022 },
      { title: '抱抱無尾熊', artist: '盧瀚霆', year: 2022 },
      { title: '仍在', artist: '陳卓賢', year: 2023 },
      { title: '夜視鏡', artist: '陳卓賢', year: 2023 },
      { title: 'Lost at First Sight', artist: '陳卓賢', year: 2024 },
      { title: 'Thank You Postman', artist: '陳卓賢', year: 2024 },
      { title: '鑿', artist: '陳卓賢', year: 2024 },
      { title: '玩偶奇遇記', artist: '陳卓賢', year: 2024 },
      { title: '地球上的最後一朵花', artist: '陳卓賢', year: 2022 },
      { title: '無答案', artist: '林家謙', year: 2024 },
      { title: '萬一你是個好人', artist: '林家謙', year: 2023 },
      { title: '怪我只敢做好人', artist: '林家謙', year: 2023 },
      { title: '夏之風物詩', artist: '林家謙', year: 2022 },
      { title: '乾', artist: '張天賦', year: 2022 },
      { title: '筆友', artist: '張天賦', year: 2024 },
      { title: '一百個未老先衰的方法', artist: '張天賦', year: 2024 },
      { title: '窮人的薔薇', artist: '陳蕾', year: 2024 },
      { title: '念', artist: '陳蕾', year: 2024 },
      { title: '致我們的夢想', artist: '鄭秀文', year: 2023 },
      { title: '三生有幸', artist: '周殷廷', year: 2024 },
      { title: '飄流教室', artist: '古巨基、呂爵安', year: 2022 },
      { title: '自我安慰', artist: '古巨基、張天賦', year: 2022 },
      { title: '第二最愛', artist: '古巨基、Tyson Yoshi', year: 2022 },
      { title: '離別的規矩', artist: '柳應廷', year: 2022 },
      { title: 'MM7', artist: '柳應廷', year: 2022 },
      { title: 'We All Are', artist: 'MIRROR', year: 2022 },
      { title: 'Catch A Vibe', artist: 'MIRROR', year: 2023 },
      { title: 'Call My Name!', artist: 'COLLAR', year: 2022 },
      { title: 'Never-never Land', artist: 'COLLAR', year: 2022 },
      { title: '給缺席的人唱首歌', artist: '馮允謙', year: 2022 },
      { title: '沒有翅膀的天使', artist: '姜濤', year: 2023 },
      { title: 'I Know', artist: '姜濤、AGA', year: 2022 },
      ...BACKFILL_2022_2024
    ]
  },
  {
    id: '2024-2026',
    label: '2024–2026',
    range: '2024 - 2026',
    description: '2024 至 2026 年最紅粵語歌',
    songs: [
      { title: '好得太過份', artist: '姜濤', year: 2024 },
      { title: '用背脊唱情歌', artist: 'Gareth.T', year: 2025 },
      { title: '說謊者', artist: '張天賦', year: 2025 },
      { title: '會再見的', artist: '馮允謙', year: 2024 },
      { title: 'On a SunnyDay', artist: '姜濤', year: 2025 },
      { title: '黑玻璃', artist: '洪嘉豪', year: 2024 },
      { title: '間歇性休眠', artist: '陳凱詠', year: 2024 },
      { title: '青春告別式', artist: '張敬軒', year: 2024 },
      { title: '九秒九', artist: '容祖兒', year: 2024 },
      { title: '岩巉', artist: '姜濤', year: 2024 },
      { title: '小心碰頭', artist: '張天賦', year: 2024 },
      { title: 'Hey Hey OK!', artist: '盧瀚霆', year: 2024 },
      { title: '懷疑人生', artist: '張天賦', year: 2025 },
      { title: '白夜行', artist: '李幸倪', year: 2025 },
      { title: '以孤獨命名', artist: '陳卓賢', year: 2024 },
      { title: '普渡眾生', artist: '林家謙', year: 2024 },
      { title: '回憶半分鐘', artist: '雲浩影', year: 2024 },
      { title: '至少做一件離譜的事', artist: 'Kiri T', year: 2024 },
      { title: '藝術與科學', artist: '林奕匡、黃妍、葉巧琳', year: 2024 },
      { title: '戀愛腦之死', artist: '陳健安', year: 2024 },
      { title: '無答案', artist: '林家謙', year: 2024 },
      { title: 'MY LIFE', artist: '盧瀚霆', year: 2024 },
      { title: '深閨', artist: '盧瀚霆', year: 2024 },
      { title: '永久損毀', artist: '張天賦、陳蕾', year: 2024 },
      { title: '隔牆有耳', artist: '張天賦', year: 2024 },
      { title: '油麻地莎士比亞', artist: '呂爵安', year: 2024 },
      { title: '黑月', artist: '姜濤', year: 2024 },
      { title: 'Every Single Time', artist: '姜濤', year: 2024 },
      { title: '50/50', artist: '謝安琪', year: 2025 },
      { title: '白色踢死兔', artist: '魏浚笙', year: 2025 },
      { title: '無糖可樂', artist: '泳兒', year: 2025 },
      { title: '逆旅', artist: 'The Hertz', year: 2025 },
      { title: '我所看見的未來', artist: '陳柏宇', year: 2025 },
      { title: '你流淚所以我流淚', artist: 'Dear Jane', year: 2025 },
      { title: '吉卜力', artist: '馮允謙', year: 2025 },
      { title: '四月物語', artist: '林家謙', year: 2025 },
      { title: '春日部', artist: '林家謙', year: 2025 },
      { title: '手印', artist: 'MIRROR', year: 2025 },
      { title: 'Heartbreaker', artist: '盧瀚霆', year: 2025 },
      { title: 'Lemonade', artist: '盧瀚霆', year: 2025 },
      { title: '你都有今日', artist: '盧瀚霆', year: 2025 },
      { title: '東邪', artist: '張天賦', year: 2025 },
      { title: '純銀子彈', artist: '呂爵安', year: 2025 },
      { title: 'Capital E', artist: '呂爵安', year: 2025 },
      { title: '悲觀主義', artist: '陳卓賢', year: 2025 },
      { title: '樹會流眼淚', artist: '陳卓賢', year: 2025 },
      { title: '給千億顆星選中的二人', artist: '陳卓賢', year: 2025 },
      { title: '我們什麼都不是', artist: '馬天佑', year: 2025 },
      { title: '流浪星球', artist: '姜濤', year: 2025 },
      { title: '白果', artist: '姜濤', year: 2025 },
      { title: '你要倔強', artist: '姜濤', year: 2025 },
      { title: '泥菩薩', artist: 'Gareth.T', year: 2025 },
      { title: '下世愛你', artist: '洪嘉豪', year: 2025 },
      { title: '親愛的', artist: '洪嘉豪', year: 2025 },
      { title: '秋葉緣', artist: '林家謙', year: 2025 },
      { title: '168.5', artist: '張天賦', year: 2025 },
      { title: '逆行', artist: '謝霆鋒', year: 2025 },
      { title: '求救的勇氣', artist: '陳蕾', year: 2025 },
      { title: '心死了幾百次', artist: '江𤒹生', year: 2025 },
      { title: '然之後', artist: '馮允謙', year: 2025 },
      { title: 'Life Is The Answer', artist: '馮允謙', year: 2025 },
      { title: 'The Best Version Of Me', artist: '衛蘭', year: 2025 },
      { title: '今繼', artist: '柳應廷', year: 2025 },
      { title: '沒終點的青春', artist: '柳應廷', year: 2025 },
      { title: '記憶倒行', artist: '柳應廷', year: 2025 },
      { title: 'SWITCH', artist: '陳凱詠', year: 2025 },
      { title: 'PTSD', artist: '陳凱詠', year: 2025 },
      { title: 'Love Me Down', artist: '邱彥筒', year: 2025 },
      { title: '哀傷和愛上算不算同音字', artist: 'Kiri T', year: 2025 },
      { title: '在愛面前投降', artist: '馮允謙', year: 2024 },
      { title: '關於後悔', artist: '陳柏宇', year: 2025 },
      { title: '不愛無壞', artist: '陳柏宇', year: 2025 },
      { title: '給失敗者的一封信', artist: 'Nowhere Boys', year: 2025 },
      { title: '想寫好的功課', artist: 'RubberBand', year: 2025 },
      { title: '痛痛快快活活去', artist: 'Pandora', year: 2025 },
      { title: '你都不知道 自己有多好', artist: 'Gareth.T', year: 2025 },
      { title: '空無之地', artist: '陳蕾', year: 2025 },
      { title: '天損之人', artist: '陳蕾', year: 2025 },
      { title: '愛情求生案內書', artist: '吳業坤', year: 2025 },
      { title: '二十還好', artist: 'KOLOR', year: 2025 },
      { title: '我感覺到', artist: '洪嘉豪、魏浚笙', year: 2025 },
      { title: '閃光', artist: '洪嘉豪', year: 2025 },
      { title: '怕悶的人 請舉手', artist: '林峯', year: 2025 },
      { title: '我又戀愛了', artist: '林峯', year: 2024 },
      { title: '百妖夜行的修行', artist: '陳凱詠', year: 2024 },
      { title: '三生有幸', artist: '周殷廷', year: 2024 },
      { title: '鑿', artist: '陳卓賢', year: 2024 },
      { title: '筆友', artist: '張天賦', year: 2024 },
      { title: '一百個未老先衰的方法', artist: '張天賦', year: 2024 },
      { title: '玩偶奇遇記', artist: '陳卓賢', year: 2024 },
      { title: '致我', artist: '盧瀚霆', year: 2024 },
      { title: '月光奏明曲', artist: '呂爵安', year: 2024 },
      { title: '拜託', artist: '洪嘉豪', year: 2024 },
      { title: '跟你分擔失落比較快樂', artist: '洪嘉豪', year: 2024 },
      { title: '念', artist: '陳蕾', year: 2024 },
      { title: '0.1秒後的世界', artist: '陳蕾', year: 2024 },
      { title: '新牌仔', artist: '李幸倪', year: 2024 },
      { title: 'Diff.', artist: '李幸倪', year: 2024 },
      { title: '神愛世人', artist: '鄧小巧', year: 2024 },
      { title: '明日明日', artist: 'Dear Jane', year: 2024 },
      ...BACKFILL_2024_2026
    ]
  }
]

// 2026 releases, discovered from the iTunes HK catalogue.
const YEAR_2026 = [
  { title: '我想過一個怎樣的人生?', artist: '方皓玟', year: 2026 },
  { title: '急口令', artist: 'CY 陳宗澤', year: 2026 },
  { title: '水裏水裏去 Water Your Day', artist: '陳凱詠', year: 2026 },
  { title: 'Is that you?', artist: '歸綽嶢', year: 2026 },
  { title: '快樂不知時日', artist: 'Dear Jane', year: 2026 },
  { title: 'Custom-made girl', artist: 'Tiab', year: 2026 },
  { title: '分擔', artist: 'Billy Choi', year: 2026 },
  { title: '真的不是故意的', artist: 'Kiri T', year: 2026 },
  { title: '脫臼', artist: '邱鋒澤', year: 2026 },
  { title: '外向型憂鬱人格', artist: '鄧小巧', year: 2026 },
  { title: '穿波鞋的惡魔', artist: '洪嘉豪', year: 2026 },
  { title: '未會遲', artist: '谷婭溦', year: 2026 },
  { title: 'Dancing Till The End', artist: 'WHIZZ', year: 2026 },
  { title: '愛情不是我強項', artist: '吳林峰', year: 2026 },
  { title: '緊急聯絡人', artist: 'Gareth.T', year: 2026 },
  { title: '連自己都不夠快樂', artist: '許靖韻', year: 2026 },
  { title: 'Deadend (活該)', artist: 'Tyson Yoshi', year: 2026 },
  { title: '當我們不再說晚安', artist: '晚安莉莉', year: 2026 },
  { title: '不是那種勵志歌', artist: '葉巧琳', year: 2026 },
  { title: '不藥而癒', artist: '衛蘭', year: 2026 },
  { title: '你忘掉比我記得的多', artist: 'OneUp', year: 2026 },
  { title: '派對後派對', artist: '黃妍', year: 2026 },
  { title: '散光', artist: '泳兒', year: 2026 },
  { title: '今世情人', artist: '周殷廷', year: 2026 },
  { title: '樓梯等你', artist: '區子琳', year: 2026 },
  { title: '想一想日日捱餐死 咪教我洩氣', artist: 'JNYBeatz', year: 2026 },
  { title: '月亮代表我', artist: 'Moon Tang', year: 2026 },
  { title: '餘地', artist: 'Serrini', year: 2026 },
  { title: '特務占士匡 Mad World', artist: '林奕匡', year: 2026 },
  { title: '大亨', artist: '林家謙', year: 2026 },
  { title: '舊酒新瓶', artist: '陳柏宇', year: 2026 },
  { title: 'I\'m alright', artist: '劉卓軒', year: 2026 },
  { title: '你快樂嗎', artist: '李幸倪', year: 2026 },
  { title: '初級大人', artist: 'ROVER', year: 2026 },
  { title: '二樓後續', artist: 'Nowhere Boys', year: 2026 },
  { title: '⼤數據以為我還愛你', artist: 'Zpecial', year: 2026 },
  { title: '大團圓結局', artist: 'sica', year: 2026 },
  { title: '你所打的號碼暫時未能接通', artist: '曾比特', year: 2026 },
  { title: '仙女座事故', artist: '陳健安', year: 2026 },
  { title: '烏合之眾', artist: 'KOLOR', year: 2026 },
  { title: '隕石與地球', artist: '鄭秀文', year: 2026 },
  { title: '我想和你虛度光陰', artist: '雲浩影', year: 2026 },
  { title: '陪多我半日好嗎', artist: '麗英', year: 2026 },
  { title: '人間缺憾美', artist: '馮允謙', year: 2026 },
  { title: '放棄的界限', artist: '張敬軒', year: 2026 },
  { title: '等等等等', artist: '容祖兒', year: 2026 },
  { title: '二缺一的美', artist: '鍾柔美', year: 2026 },
  { title: 'Bye Bye Bye', artist: '炎明熹', year: 2026 },
  { title: '淚光', artist: 'COLLAR', year: 2026 },
  { title: '已出之物', artist: '魏浚笙', year: 2026 },
  { title: '一杯', artist: 'RubberBand', year: 2026 },
  { title: '人類愛情學', artist: '陳蕾', year: 2026 },
  { title: '至少相擁沒錯', artist: '張天賦', year: 2026 },
  { title: '靈光一千閃', artist: 'Pandora', year: 2026 },
  { title: '光透進來的地方', artist: '岑寧兒', year: 2026 },
  { title: '別讓愛被愛人殺死', artist: '姚焯菲', year: 2026 },
  { title: '大楷人生', artist: 'per se', year: 2026 },
]

// ---- Per-year categories ---------------------------------------------------
// A year may have several songs per artist, so prefer entries whose artist has
// a healthy pool in that year: that keeps the 4 answer options varied.
function yearPoolScore(song, pool) {
  const tokens = artistTokens(song.artist)
  let best = 0
  for (const t of tokens) {
    const n = pool.filter((o) => artistTokens(o.artist).includes(t)).length
    if (n > best) best = n
  }
  return best
}

// Every song that appears anywhere, deduped by title+artist.
const ALL_SONGS = []
{
  const seen = new Set()
  for (const bucket of [...YEAR_BUCKETS, { songs: YEAR_2026 }]) {
    for (const song of bucket.songs) {
      const key = `${song.title}\u0000${song.artist}`
      if (seen.has(key)) continue
      seen.add(key)
      ALL_SONGS.push(song)
    }
  }
}

// One category per calendar year. Songs are ordered most-connected-artist first,
// and a year is only offered once it has enough material to be playable.
function buildYearCategories() {
  const years = [...new Set(ALL_SONGS.map((s) => s.year))].sort((a, b) => a - b)
  const out = []
  for (const year of years) {
    const songs = ALL_SONGS.filter((s) => s.year === year)
    if (songs.length < 12) continue
    const ordered = songs
      .slice()
      .sort((a, b) => yearPoolScore(b, songs) - yearPoolScore(a, songs))
    out.push({
      id: String(year),
      label: String(year),
      group: '年份歌單',
      range: String(year),
      description: `${year} 年粵語歌`,
      songs: ordered
    })
  }
  return out
}

// ---- Artist selections (not year-based) -----------------------------------
const ARTIST_CATEGORIES = [
  {
    id: 'eason',
    label: '陳奕迅',
    group: '歌手精選',
    range: 'Eason Chan',
    description: '陳奕迅粵語精選',
    songs: EASON
  },
  {
    id: 'endy',
    label: '周國賢',
    group: '歌手精選',
    range: 'Endy Chow',
    description: '周國賢粵語精選',
    songs: ENDY
  },
  {
    id: 'terence',
    label: '林家謙',
    group: '歌手精選',
    range: 'Terence Lam',
    description: '林家謙粵語精選',
    songs: TERENCE
  },
  {
    id: 'trio',
    label: '三位混合',
    group: '歌手精選',
    range: 'Eason + Endy + Terence',
    description: '陳奕迅 + 周國賢 + 林家謙 混合',
    songs: [...EASON, ...ENDY, ...TERENCE]
  }
]

// What the API and UI actually expose: one category per calendar year
// (2020, 2021, 2022, …) followed by the artist selections.
export const CATEGORIES = [...buildYearCategories(), ...ARTIST_CATEGORIES]
