// Curated Hong Kong Cantonese hit playlists by year range.
// Each category holds ~100 of the most popular Cantonese songs in HK for that period.
// Audio previews are resolved at runtime from the iTunes Search API (see preview.js).

// ---- Artist favourites (Cantonese only) ----------------------------------
const EASON = [
  { title: '富士山下', artist: '陳奕迅', year: 2006 },
  { title: '浮誇', artist: '陳奕迅', year: 2005 },
  { title: 'K歌之王', artist: '陳奕迅', year: 2000 },
  { title: '明年今日', artist: '陳奕迅', year: 2002 },
  { title: '單車', artist: '陳奕迅', year: 2001 },
  { title: '夕陽無限好', artist: '陳奕迅', year: 2005 },
  { title: '葡萄成熟時', artist: '陳奕迅', year: 2005 },
  { title: '陀飛輪', artist: '陳奕迅', year: 2010 },
  { title: '沙龍', artist: '陳奕迅', year: 2009 },
  { title: '苦瓜', artist: '陳奕迅', year: 2011 },
  { title: '任我行', artist: '陳奕迅', year: 2013 },
  { title: '無條件', artist: '陳奕迅', year: 2015 },
  { title: '無人之境', artist: '陳奕迅', year: 2009 },
  { title: '落花流水', artist: '陳奕迅', year: 2006 },
  { title: '人來人往', artist: '陳奕迅', year: 2002 },
  { title: 'Shall We Talk', artist: '陳奕迅', year: 2001 },
  { title: '最佳損友', artist: '陳奕迅', year: 2005 },
  { title: '我的快樂時代', artist: '陳奕迅', year: 2000 },
  { title: '歲月如歌', artist: '陳奕迅', year: 2003 },
  { title: '十面埋伏', artist: '陳奕迅', year: 2003 },
  { title: '阿牛', artist: '陳奕迅', year: 2006 },
  { title: '綿綿', artist: '陳奕迅', year: 2001 },
  { title: '孤獨探戈', artist: '陳奕迅', year: 2005 },
  { title: '六月飛霜', artist: '陳奕迅', year: 2011 },
  { title: '天下無雙', artist: '陳奕迅', year: 2001 },
  { title: '與我常在', artist: '陳奕迅', year: 2000 },
  { title: '黑暗中漫舞', artist: '陳奕迅', year: 2001 },
  { title: '失戀太少', artist: '陳奕迅', year: 2001 },
  { title: '七百年後', artist: '陳奕迅', year: 2009 },
  { title: '幸福摩天輪', artist: '陳奕迅', year: 2000 },
  { title: '一絲不掛', artist: '陳奕迅', year: 2010 },
  { title: '大開眼戒', artist: '陳奕迅', year: 2001 },
  { title: '1874', artist: '陳奕迅', year: 2005 },
  { title: '反高潮', artist: '陳奕迅', year: 2001 },
  { title: '防不勝防', artist: '陳奕迅', year: 2001 },
  { title: '粵語殘片', artist: '陳奕迅', year: 2001 },
  { title: '今天只做一件事', artist: '陳奕迅', year: 2001 },
  { title: '今日', artist: '陳奕迅', year: 2005 },
  { title: '四季', artist: '陳奕迅', year: 2016 },
  { title: '黃金時代', artist: '陳奕迅', year: 2001 },
  { title: '重口味', artist: '陳奕迅', year: 2012 },
  { title: '碌卡', artist: '陳奕迅', year: 2012 },
  { title: '主旋律', artist: '陳奕迅', year: 2013 },
  { title: '告別娑婆', artist: '陳奕迅', year: 2013 },
  { title: '暴殄天物', artist: '陳奕迅', year: 2008 },
  { title: '怕死', artist: '陳奕迅', year: 2008 },
  { title: '心深傷透', artist: '陳奕迅', year: 2006 },
  { title: '我不好愛', artist: '陳奕迅', year: 2006 },
  { title: '完', artist: '陳奕迅', year: 2010 },
  { title: '張氏情歌', artist: '陳奕迅', year: 2011 },
  { title: '吟遊詩人', artist: '陳奕迅', year: 2011 },
  { title: '致明日的舞', artist: '陳奕迅', year: 2020 },
  { title: '是但求其愛', artist: '陳奕迅', year: 2020 },
  { title: '你給我聽好', artist: '陳奕迅', year: 2020 },
  { title: '人啊人', artist: '陳奕迅', year: 2022 },
  { title: '塵大師', artist: '陳奕迅', year: 2023 },
  { title: '盲婚啞嫁', artist: '陳奕迅', year: 2023 }
]

const ENDY = [
  { title: '星塵', artist: '周國賢', year: 2014 },
  { title: '橡筋', artist: '周國賢', year: 2016 },
  { title: '物極必反', artist: '周國賢', year: 2017 },
  { title: '時空', artist: '周國賢', year: 2018 },
  { title: '有時', artist: '周國賢', year: 2015 },
  { title: '未完 待續', artist: '周國賢', year: 2018 },
  { title: '地下街', artist: '周國賢', year: 2006 },
  { title: '目黑', artist: '周國賢', year: 2006 },
  { title: '14天', artist: '周國賢', year: 2012 },
  { title: '漢城沉沒了', artist: '周國賢', year: 2010 },
  { title: '離魂記', artist: '周國賢', year: 2015 },
  { title: 'Children Song', artist: '周國賢', year: 2016 },
  { title: '赤城千葉', artist: '周國賢', year: 2012 },
  { title: '密封罩', artist: '周國賢', year: 2014 },
  { title: 'Fall', artist: '周國賢', year: 2019 },
  { title: '塵世美', artist: '周國賢', year: 2021 },
  { title: '太平道', artist: '周國賢', year: 2013 },
  { title: '身後身', artist: '周國賢', year: 2021 },
  { title: '雙兒', artist: '周國賢', year: 2022 },
  { title: '鬼怒川', artist: '周國賢', year: 2015 },
  { title: '模稜兩可', artist: '周國賢', year: 2016 },
  { title: '不敵', artist: '周國賢', year: 2016 },
  { title: '黑眼圈', artist: '周國賢', year: 2014 },
  { title: '東區走廊', artist: '周國賢', year: 2014 },
  { title: 'Dreamcatcher', artist: '周國賢', year: 2017 },
  { title: '今生不回家', artist: '周國賢', year: 2020 },
  { title: '再見有時', artist: '周國賢', year: 2024 },
  { title: '逃生門', artist: '周國賢', year: 2020 },
  { title: '天秤', artist: '周國賢', year: 2020 },
  { title: '從此世界多了一分鐘', artist: '周國賢', year: 2022 },
  { title: '好自為之', artist: '周國賢', year: 2021 },
  { title: '我們都不是無辜的', artist: '周國賢', year: 2019 },
  { title: '覺醒字幕組', artist: '周國賢', year: 2020 },
  { title: '陽光點的歌', artist: '周國賢', year: 2017 },
  { title: '溫室氣體', artist: '周國賢', year: 2019 },
  { title: '永遠很近', artist: '周國賢', year: 2016 },
  { title: '撲火', artist: '周國賢', year: 2021 },
  { title: '我是傳奇', artist: '周國賢', year: 2019 },
  { title: '無畏', artist: '周國賢', year: 2019 },
  { title: '極樂', artist: '周國賢', year: 2021 },
  { title: '天馬行空', artist: '周國賢', year: 2017 },
  { title: '童話', artist: '周國賢', year: 2019 }
]

const TERENCE = [
  { title: '一人之境', artist: '林家謙', year: 2020 },
  { title: '特倫斯夢遊仙境', artist: '林家謙', year: 2020 },
  { title: '時光倒流一句話', artist: '林家謙', year: 2020 },
  { title: '拼命無恙', artist: '林家謙', year: 2020 },
  { title: '下一位前度', artist: '林家謙', year: 2019 },
  { title: '神奇的糊塗魔藥', artist: '林家謙', year: 2021 },
  { title: '在空中的這一秒', artist: '林家謙', year: 2021 },
  { title: '難道喜歡處女座', artist: '林家謙', year: 2021 },
  { title: '聽風', artist: '林家謙', year: 2021 },
  { title: '拋物線', artist: '林家謙', year: 2020 },
  { title: 'just carry on', artist: '林家謙', year: 2020 },
  { title: '某種老朋友', artist: '林家謙', year: 2022 },
  { title: '記得', artist: '林家謙', year: 2022 },
  { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
  { title: '夏之風物詩', artist: '林家謙', year: 2022 },
  { title: 'doodoodoo', artist: '林家謙', year: 2022 },
  { title: '難道我還未夠難', artist: '林家謙', year: 2022 },
  { title: '小林不動產', artist: '林家謙', year: 2023 },
  { title: '怪我只敢做好人', artist: '林家謙', year: 2023 },
  { title: '萬一你是個好人', artist: '林家謙', year: 2023 },
  { title: '流離者的海', artist: '林家謙', year: 2023 },
  { title: '你的世界', artist: '林家謙', year: 2023 },
  { title: '事與願違', artist: '林家謙', year: 2023 },
  { title: '靈魂出竅練習曲', artist: '林家謙', year: 2023 },
  { title: '無答案', artist: '林家謙', year: 2024 },
  { title: '喃嘸師感官漫遊', artist: '林家謙', year: 2024 },
  { title: '普渡眾生', artist: '林家謙', year: 2024 },
  { title: '春日部', artist: '林家謙', year: 2024 },
  { title: '四月物語', artist: '林家謙', year: 2025 },
  { title: '夏日之子', artist: '林家謙', year: 2025 },
  { title: '秋葉緣', artist: '林家謙', year: 2025 },
  { title: '冬季限定', artist: '林家謙', year: 2025 },
  { title: '每當變幻時', artist: '林家謙', year: 2025 }
]

export const CATEGORIES = [
  {
    id: '2020-2022',
    label: '2020–2022',
    range: '2020 - 2022',
    description: '2020 至 2022 年最紅粵語歌',
    songs: [
      { title: '記憶棉', artist: '張天賦', year: 2021 },
      { title: 'E先生 連環不幸事件', artist: '呂爵安', year: 2021 },
      { title: 'Dear My Friend,', artist: '姜濤', year: 2021 },
      { title: '一人之境', artist: '林家謙', year: 2020 },
      { title: '呼吸有害', artist: '莫文蔚', year: 2020 },
      { title: '銀河修理員', artist: 'Dear Jane', year: 2020 },
      { title: '作品的說話', artist: '姜濤', year: 2022 },
      { title: '小心地滑', artist: '張天賦', year: 2022 },
      { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
      { title: '到底發生過什麼事', artist: 'Dear Jane', year: 2022 },
      { title: '老派約會之必要', artist: '張天賦', year: 2022 },
      { title: '留一天與你喘息', artist: '陳卓賢', year: 2022 },
      { title: '俏郎君', artist: '張敬軒', year: 2021 },
      { title: '反對無效', artist: '張天賦', year: 2021 },
      { title: '蒙著嘴說愛你', artist: '姜濤', year: 2020 },
      { title: '是但求其愛', artist: '陳奕迅', year: 2020 },
      { title: 'BOSS', artist: 'MIRROR', year: 2021 },
      { title: 'Ciao', artist: 'RubberBand', year: 2021 },
      { title: '小諧星', artist: '呂爵安', year: 2021 },
      { title: '不可愛教主', artist: '盧瀚霆', year: 2021 },
      { title: 'Megahit', artist: '盧瀚霆', year: 2021 },
      { title: 'WARRIOR', artist: 'MIRROR', year: 2021 },
      { title: 'IGNITED', artist: 'MIRROR', year: 2020 },
      { title: 'Master Class', artist: '姜濤', year: 2021 },
      { title: '神奇的糊塗魔藥', artist: '林家謙', year: 2021 },
      { title: '狂人日記', artist: '柳應廷', year: 2021 },
      { title: '鏡中鏡', artist: '姜濤', year: 2022 },
      { title: '賽勒斯的愛', artist: '張敬軒', year: 2022 },
      { title: '人啊人', artist: '陳奕迅', year: 2022 },
      { title: '多喝水', artist: '鄭融', year: 2021 },
      { title: '先哭為敬', artist: '鄭欣宜', year: 2021 },
      { title: '留下來的人', artist: 'C AllStar', year: 2021 },
      { title: '東京人壽', artist: '容祖兒', year: 2020 },
      { title: '地球來的人', artist: '馮允謙', year: 2020 },
      { title: '無力感', artist: '許廷鏗', year: 2020 },
      { title: 'See You Next Time', artist: 'AGA', year: 2020 },
      { title: '暫定', artist: '關智斌', year: 2020 },
      { title: '感情這回事', artist: '陳柏宇', year: 2020 },
      { title: '零分', artist: 'JUDE', year: 2020 },
      { title: '哀的美敦書', artist: 'Dear Jane', year: 2020 },
      { title: '人話', artist: '方皓玟', year: 2020 },
      { title: '風的形狀', artist: '岑寧兒', year: 2021 },
      { title: '集合吧！地球保衛隊', artist: 'C AllStar', year: 2021 },
      { title: '荊棘海', artist: '泳兒', year: 2021 },
      { title: '係咁先啦', artist: 'MC $oHo & KidNey', year: 2021 },
      { title: '一表人才', artist: '呂爵安、邱鋒澤', year: 2021 },
      { title: 'My Apple Pie', artist: '呂爵安', year: 2021 },
      { title: '時光倒流一句話', artist: '林家謙', year: 2020 },
      { title: '離不開', artist: '謝安琪', year: 2021 },
      { title: '風雨不改', artist: '姜濤', year: 2022 },
      { title: '永順街39號', artist: '盧瀚霆', year: 2022 },
      { title: 'Elevator', artist: '呂爵安', year: 2022 },
      { title: '離別的規矩', artist: '柳應廷', year: 2022 },
      { title: '人類群星閃耀時', artist: '柳應廷', year: 2021 },
      { title: 'DWBF', artist: '陳卓賢', year: 2021 },
      { title: '神隊友', artist: '盧瀚霆', year: 2020 },
      { title: '正式開始', artist: '陳卓賢', year: 2020 },
      { title: 'Distance', artist: '陳卓賢', year: 2022 },
      { title: '地球上的最後一朵花', artist: '陳卓賢', year: 2022 },
      { title: 'King Kong', artist: '盧瀚霆', year: 2022 },
      { title: '飄流教室', artist: '古巨基、呂爵安', year: 2022 },
      { title: '自我安慰', artist: '古巨基、張天賦', year: 2022 },
      { title: 'We All Are', artist: 'MIRROR', year: 2022 },
      { title: 'Never-never Land', artist: 'COLLAR', year: 2022 },
      { title: '第二最愛', artist: '古巨基、Tyson Yoshi', year: 2022 },
      { title: 'I Know', artist: '姜濤', year: 2021 },
      { title: '隔離', artist: '陳凱詠', year: 2020 },
      { title: '別為我好', artist: '許靖韻、林奕匡', year: 2020 },
      { title: '凡人不懂愛', artist: '胡鴻鈞', year: 2020 },
      { title: '沒身份妒忌', artist: '胡鴻鈞', year: 2020 },
      { title: '拼命無恙', artist: '林家謙', year: 2020 },
      { title: '我們的基因', artist: '謝安琪', year: 2020 },
      { title: '逃生門', artist: '周國賢', year: 2020 },
      { title: '難道喜歡處女座', artist: '林家謙', year: 2021 },
      { title: '思念即地獄', artist: '馮允謙', year: 2021 },
      { title: '人類不宜飛行', artist: 'Dear Jane', year: 2021 },
      { title: '聖馬力諾之心', artist: 'Dear Jane', year: 2021 },
      { title: '網絡安全隱患', artist: 'Serrini', year: 2020 },
      { title: '離原', artist: 'Serrini', year: 2021 },
      { title: '真話的清高', artist: '炎明熹', year: 2021 },
      { title: '焰', artist: '炎明熹', year: 2022 },
      { title: '我不如', artist: '曾比特', year: 2021 },
      { title: '逆時車站', artist: '洪嘉豪', year: 2021 },
      { title: '理性與任性之間', artist: 'AGA', year: 2021 },
      { title: '幸福門', artist: '李幸倪', year: 2020 },
      { title: '睡到三點', artist: '193', year: 2021 },
      { title: '哭牆', artist: '谷婭溦', year: 2020 },
      { title: '突如其來的心跳感覺', artist: '盧瀚霆、呂爵安', year: 2021 },
      { title: '黑之呼吸', artist: '江𤒹生', year: 2021 },
      { title: '我們很帥', artist: 'ERROR', year: 2021 },
      { title: '低半度', artist: '衛蘭', year: 2020 },
      { title: '原來談戀愛是這麼一回事', artist: '姚焯菲', year: 2021 },
      { title: '下流社會', artist: '陳蕾', year: 2022 },
      { title: '凡星', artist: '陳蕾', year: 2022 },
      { title: '豐乳肥臀', artist: '鄭欣宜', year: 2022 },
      { title: '我地', artist: '鄭欣宜', year: 2022 },
      { title: '憶年', artist: '謝安琪', year: 2022 },
      { title: '笑住喊', artist: 'Gareth.T', year: 2022 },
      { title: '我也難過的', artist: '吳林峰、謝芊彤', year: 2022 },
      { title: "Freakin' Nightmare", artist: '馮允謙', year: 2022 }
    ]
  },
  {
    id: '2022-2024',
    label: '2022–2024',
    range: '2022 - 2024',
    description: '2022 至 2024 年最紅粵語歌',
    songs: [
      { title: '濤', artist: '姜濤', year: 2023 },
      { title: '作品的說話', artist: '姜濤', year: 2022 },
      { title: '好得太過份', artist: '姜濤', year: 2024 },
      { title: '隱形遊樂場', artist: '張敬軒', year: 2023 },
      { title: '邊一個發明了ENCORE', artist: '林家謙', year: 2022 },
      { title: '會再見的', artist: '馮允謙', year: 2024 },
      { title: '到底發生過什麼事', artist: 'Dear Jane', year: 2022 },
      { title: '老派約會之必要', artist: '張天賦', year: 2022 },
      { title: '小心地滑', artist: '張天賦', year: 2022 },
      { title: '留一天與你喘息', artist: '陳卓賢', year: 2022 },
      { title: 'Dummy', artist: '姜濤', year: 2023 },
      { title: '黑玻璃', artist: '洪嘉豪', year: 2024 },
      { title: '世一', artist: '張天賦', year: 2023 },
      { title: '與我無關', artist: '張天賦', year: 2023 },
      { title: '以孤獨命名', artist: '陳卓賢', year: 2024 },
      { title: '偷情', artist: '盧瀚霆', year: 2023 },
      { title: '鏡中鏡', artist: '姜濤', year: 2022 },
      { title: '普渡眾生', artist: '林家謙', year: 2024 },
      { title: '岩巉', artist: '姜濤', year: 2023 },
      { title: '黑月', artist: '姜濤', year: 2024 },
      { title: '追', artist: '姜濤', year: 2023 },
      { title: '抽', artist: '張天賦', year: 2023 },
      { title: '永順街39號', artist: '盧瀚霆', year: 2022 },
      { title: 'Every Single Time', artist: '姜濤', year: 2024 },
      { title: '風雨不改', artist: '姜濤', year: 2022 },
      { title: '再見 寧靜海', artist: '陳卓賢', year: 2023 },
      { title: '小心碰頭', artist: '張天賦', year: 2024 },
      { title: '隔牆有耳', artist: '張天賦', year: 2024 },
      { title: '某種老朋友', artist: '林家謙', year: 2022 },
      { title: '青春告別式', artist: '張敬軒', year: 2024 },
      { title: '賽勒斯的愛', artist: '張敬軒', year: 2022 },
      { title: '間歇性休眠', artist: '陳凱詠', year: 2024 },
      { title: '九秒九', artist: '容祖兒', year: 2024 },
      { title: '回憶半分鐘', artist: '雲浩影', year: 2024 },
      { title: 'Dum Dum', artist: '李幸倪', year: 2023 },
      { title: '伸縮自如的愛', artist: '陳蕾', year: 2023 },
      { title: '下流社會', artist: '陳蕾', year: 2022 },
      { title: '至少做一件離譜的事', artist: 'Kiri T', year: 2024 },
      { title: '一把火', artist: 'Lolly Talk', year: 2023 },
      { title: '不如散步', artist: 'RubberBand', year: 2023 },
      { title: '收到收到', artist: '馮允謙', year: 2023 },
      { title: '報復式浪漫', artist: '馮允謙', year: 2022 },
      { title: '救命稻草', artist: '張天賦', year: 2023 },
      { title: '永久損毀', artist: '張天賦、陳蕾', year: 2023 },
      { title: '人啊人', artist: '陳奕迅', year: 2022 },
      { title: '盲婚啞嫁', artist: '陳奕迅', year: 2023 },
      { title: '憶年', artist: '謝安琪', year: 2022 },
      { title: '笑住喊', artist: 'Gareth.T', year: 2022 },
      { title: '我也難過的', artist: '吳林峰、謝芊彤', year: 2022 },
      { title: "Freakin' Nightmare", artist: '馮允謙', year: 2022 },
      { title: 'Little Magic', artist: '炎明熹', year: 2023 },
      { title: '仍然是那個少年', artist: '陳健安', year: 2023 },
      { title: '戀愛腦之死', artist: '陳健安', year: 2024 },
      { title: '藝術與科學', artist: '林奕匡、黃妍、葉巧琳', year: 2024 },
      { title: 'Elevator', artist: '呂爵安', year: 2022 },
      { title: 'LOVERSE', artist: '呂爵安', year: 2023 },
      { title: 'E先生 愛人執照', artist: '呂爵安', year: 2023 },
      { title: '油麻地莎士比亞', artist: '呂爵安', year: 2024 },
      { title: '月光奏明曲', artist: '呂爵安', year: 2024 },
      { title: '漸漸我們', artist: '呂爵安、陳凱詠', year: 2024 },
      { title: 'Again!', artist: '呂爵安', year: 2023 },
      { title: 'MONEY', artist: '盧瀚霆', year: 2023 },
      { title: 'Hey Hey OK!', artist: '盧瀚霆', year: 2024 },
      { title: '深閨', artist: '盧瀚霆', year: 2024 },
      { title: 'MY LIFE', artist: '盧瀚霆', year: 2024 },
      { title: '致我', artist: '盧瀚霆', year: 2024 },
      { title: '浪漫殺死巨蟹座', artist: '盧瀚霆', year: 2023 },
      { title: 'Mr. Stranger', artist: '盧瀚霆', year: 2022 },
      { title: 'King Kong', artist: '盧瀚霆', year: 2022 },
      { title: '抱抱無尾熊', artist: '盧瀚霆', year: 2022 },
      { title: '仍在', artist: '陳卓賢', year: 2023 },
      { title: '夜視鏡', artist: '陳卓賢', year: 2023 },
      { title: 'Lost at First Sight', artist: '陳卓賢', year: 2024 },
      { title: 'Thank You Postman', artist: '陳卓賢', year: 2024 },
      { title: '鑿', artist: '陳卓賢', year: 2024 },
      { title: '玩偶奇遇記', artist: '陳卓賢', year: 2024 },
      { title: '地球上的最後一朵花', artist: '陳卓賢', year: 2022 },
      { title: '無答案', artist: '林家謙', year: 2024 },
      { title: '萬一你是個好人', artist: '林家謙', year: 2023 },
      { title: '怪我只敢做好人', artist: '林家謙', year: 2023 },
      { title: '夏之風物詩', artist: '林家謙', year: 2022 },
      { title: '乾', artist: '張天賦', year: 2022 },
      { title: '筆友', artist: '張天賦', year: 2024 },
      { title: '一百個未老先衰的方法', artist: '張天賦', year: 2024 },
      { title: '窮人的薔薇', artist: '陳蕾', year: 2024 },
      { title: '念', artist: '陳蕾', year: 2024 },
      { title: '致我們的夢想', artist: '鄭秀文', year: 2023 },
      { title: '三生有幸', artist: '周殷廷', year: 2024 },
      { title: '飄流教室', artist: '古巨基、呂爵安', year: 2022 },
      { title: '自我安慰', artist: '古巨基、張天賦', year: 2022 },
      { title: '第二最愛', artist: '古巨基、Tyson Yoshi', year: 2022 },
      { title: '離別的規矩', artist: '柳應廷', year: 2022 },
      { title: 'MM7', artist: '柳應廷', year: 2022 },
      { title: 'We All Are', artist: 'MIRROR', year: 2022 },
      { title: 'Catch A Vibe', artist: 'MIRROR', year: 2023 },
      { title: 'Call My Name!', artist: 'COLLAR', year: 2022 },
      { title: 'Never-never Land', artist: 'COLLAR', year: 2022 },
      { title: '給缺席的人唱首歌', artist: '馮允謙', year: 2022 },
      { title: '沒有翅膀的天使', artist: '姜濤', year: 2023 },
      { title: 'I Know', artist: '姜濤、AGA', year: 2022 }
    ]
  },
  {
    id: '2024-2026',
    label: '2024–2026',
    range: '2024 - 2026',
    description: '2024 至 2026 年最紅粵語歌',
    songs: [
      { title: '好得太過份', artist: '姜濤', year: 2024 },
      { title: '用背脊唱情歌', artist: 'Gareth.T', year: 2025 },
      { title: '說謊者', artist: '張天賦', year: 2025 },
      { title: '會再見的', artist: '馮允謙', year: 2024 },
      { title: 'On a SunnyDay', artist: '姜濤', year: 2025 },
      { title: '黑玻璃', artist: '洪嘉豪', year: 2024 },
      { title: '間歇性休眠', artist: '陳凱詠', year: 2024 },
      { title: '青春告別式', artist: '張敬軒', year: 2024 },
      { title: '九秒九', artist: '容祖兒', year: 2024 },
      { title: '岩巉', artist: '姜濤', year: 2024 },
      { title: '小心碰頭', artist: '張天賦', year: 2024 },
      { title: 'Hey Hey OK!', artist: '盧瀚霆', year: 2024 },
      { title: '懷疑人生', artist: '張天賦', year: 2025 },
      { title: '白夜行', artist: '李幸倪', year: 2025 },
      { title: '以孤獨命名', artist: '陳卓賢', year: 2024 },
      { title: '普渡眾生', artist: '林家謙', year: 2024 },
      { title: '回憶半分鐘', artist: '雲浩影', year: 2024 },
      { title: '至少做一件離譜的事', artist: 'Kiri T', year: 2024 },
      { title: '藝術與科學', artist: '林奕匡、黃妍、葉巧琳', year: 2024 },
      { title: '戀愛腦之死', artist: '陳健安', year: 2024 },
      { title: '無答案', artist: '林家謙', year: 2024 },
      { title: 'MY LIFE', artist: '盧瀚霆', year: 2024 },
      { title: '深閨', artist: '盧瀚霆', year: 2024 },
      { title: '永久損毀', artist: '張天賦、陳蕾', year: 2024 },
      { title: '隔牆有耳', artist: '張天賦', year: 2024 },
      { title: '油麻地莎士比亞', artist: '呂爵安', year: 2024 },
      { title: '黑月', artist: '姜濤', year: 2024 },
      { title: 'Every Single Time', artist: '姜濤', year: 2024 },
      { title: '50/50', artist: '謝安琪', year: 2025 },
      { title: '白色踢死兔', artist: '魏浚笙', year: 2025 },
      { title: '無糖可樂', artist: '泳兒', year: 2025 },
      { title: '逆旅', artist: 'The Hertz', year: 2025 },
      { title: '我所看見的未來', artist: '陳柏宇', year: 2025 },
      { title: '你流淚所以我流淚', artist: 'Dear Jane', year: 2025 },
      { title: '吉卜力', artist: '馮允謙', year: 2025 },
      { title: '四月物語', artist: '林家謙', year: 2025 },
      { title: '春日部', artist: '林家謙', year: 2025 },
      { title: '手印', artist: 'MIRROR', year: 2025 },
      { title: 'Heartbreaker', artist: '盧瀚霆', year: 2025 },
      { title: 'Lemonade', artist: '盧瀚霆', year: 2025 },
      { title: '你都有今日', artist: '盧瀚霆', year: 2025 },
      { title: '東邪', artist: '張天賦', year: 2025 },
      { title: '純銀子彈', artist: '呂爵安', year: 2025 },
      { title: 'Capital E', artist: '呂爵安', year: 2025 },
      { title: '悲觀主義', artist: '陳卓賢', year: 2025 },
      { title: '樹會流眼淚', artist: '陳卓賢', year: 2025 },
      { title: '給千億顆星選中的二人', artist: '陳卓賢', year: 2025 },
      { title: '我們什麼都不是', artist: '馬天佑', year: 2025 },
      { title: '流浪星球', artist: '姜濤', year: 2025 },
      { title: '白果', artist: '姜濤', year: 2025 },
      { title: '你要倔強', artist: '姜濤', year: 2025 },
      { title: '泥菩薩', artist: 'Gareth.T', year: 2025 },
      { title: '下世愛你', artist: '洪嘉豪', year: 2025 },
      { title: '親愛的', artist: '洪嘉豪', year: 2025 },
      { title: '秋葉緣', artist: '林家謙', year: 2025 },
      { title: '168.5', artist: '張天賦', year: 2025 },
      { title: '逆行', artist: '謝霆鋒', year: 2025 },
      { title: '求救的勇氣', artist: '陳蕾', year: 2025 },
      { title: '心死了幾百次', artist: '江𤒹生', year: 2025 },
      { title: '然之後', artist: '馮允謙', year: 2025 },
      { title: 'Life Is The Answer', artist: '馮允謙', year: 2025 },
      { title: 'The Best Version Of Me', artist: '衛蘭', year: 2025 },
      { title: '今繼', artist: '柳應廷', year: 2025 },
      { title: '沒終點的青春', artist: '柳應廷', year: 2025 },
      { title: '記憶倒行', artist: '柳應廷', year: 2025 },
      { title: 'SWITCH', artist: '陳凱詠', year: 2025 },
      { title: 'PTSD', artist: '陳凱詠', year: 2025 },
      { title: 'Love Me Down', artist: '邱彥筒', year: 2025 },
      { title: '哀傷和愛上算不算同音字', artist: 'Kiri T', year: 2025 },
      { title: '在愛面前投降', artist: '馮允謙', year: 2024 },
      { title: '關於後悔', artist: '陳柏宇', year: 2025 },
      { title: '不愛無壞', artist: '陳柏宇', year: 2025 },
      { title: '給失敗者的一封信', artist: 'Nowhere Boys', year: 2025 },
      { title: '想寫好的功課', artist: 'RubberBand', year: 2025 },
      { title: '痛痛快快活活去', artist: 'Pandora', year: 2025 },
      { title: '你都不知道 自己有多好', artist: 'Gareth.T', year: 2025 },
      { title: '空無之地', artist: '陳蕾', year: 2025 },
      { title: '天損之人', artist: '陳蕾', year: 2025 },
      { title: '愛情求生案內書', artist: '吳業坤', year: 2025 },
      { title: '二十還好', artist: 'KOLOR', year: 2025 },
      { title: '我感覺到', artist: '洪嘉豪、魏浚笙', year: 2025 },
      { title: '閃光', artist: '洪嘉豪', year: 2025 },
      { title: '怕悶的人 請舉手', artist: '林峯', year: 2025 },
      { title: '我又戀愛了', artist: '林峯', year: 2024 },
      { title: '百妖夜行的修行', artist: '陳凱詠', year: 2024 },
      { title: '三生有幸', artist: '周殷廷', year: 2024 },
      { title: '鑿', artist: '陳卓賢', year: 2024 },
      { title: '筆友', artist: '張天賦', year: 2024 },
      { title: '一百個未老先衰的方法', artist: '張天賦', year: 2024 },
      { title: '玩偶奇遇記', artist: '陳卓賢', year: 2024 },
      { title: '致我', artist: '盧瀚霆', year: 2024 },
      { title: '月光奏明曲', artist: '呂爵安', year: 2024 },
      { title: '拜託', artist: '洪嘉豪', year: 2024 },
      { title: '跟你分擔失落比較快樂', artist: '洪嘉豪', year: 2024 },
      { title: '念', artist: '陳蕾', year: 2024 },
      { title: '0.1秒後的世界', artist: '陳蕾', year: 2024 },
      { title: '新牌仔', artist: '李幸倪', year: 2024 },
      { title: 'Diff.', artist: '李幸倪', year: 2024 },
      { title: '神愛世人', artist: '鄧小巧', year: 2024 },
      { title: '明日明日', artist: 'Dear Jane', year: 2024 }
    ]
  },
  {
    id: 'eason',
    label: '陳奕迅',
    group: '歌手精選',
    range: 'Eason Chan',
    description: '陳奕迅粵語精選',
    songs: EASON
  },
  {
    id: 'endy',
    label: '周國賢',
    group: '歌手精選',
    range: 'Endy Chow',
    description: '周國賢粵語精選',
    songs: ENDY
  },
  {
    id: 'terence',
    label: '林家謙',
    group: '歌手精選',
    range: 'Terence Lam',
    description: '林家謙粵語精選',
    songs: TERENCE
  },
  {
    id: 'trio',
    label: '三位混合',
    group: '歌手精選',
    range: 'Eason + Endy + Terence',
    description: '陳奕迅 + 周國賢 + 林家謙 混合',
    songs: [...EASON, ...ENDY, ...TERENCE]
  }
]
